---
- name: Ionice
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.7

  tasks:
    - name: Install needed packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - fio

    - name: Copy files to locations
      copy:
        src: "{{ item.file }}"
        dest: "{{ item.loc }}/"
      loop:
        - { file: "iotest.sh", loc: "/root" }
        - { file: "rthread.fio", loc: "/root" }

    - name: Set script permission
      file:
        path: "/root/iotest.sh"
        mode: "u+rx"

